package harkkatyo.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import harkkatyo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.04 12:46:30 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JoukkueTest {



  // Generated by ComTest BEGIN
  /** testGetNimi24 */
  @Test
  public void testGetNimi24() {    // Joukkue: 24
    Joukkue lumo = new Joukkue(); 
    lumo.vastaaLumo(); 
    { String _l_=lumo.getNimi(),_r_="Lumo"; if ( !_l_.matches(_r_) ) fail("From: Joukkue line: 27" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi60 */
  @Test
  public void testRekisteroi60() {    // Joukkue: 60
    Joukkue lumo = new Joukkue(); 
    assertEquals("From: Joukkue line: 62", 0, lumo.getIdNro()); 
    lumo.rekisteroi(); 
    Joukkue sirius = new Joukkue(); 
    sirius.rekisteroi(); 
    int n1 = lumo.getIdNro(); 
    int n2 = sirius.getIdNro(); 
    assertEquals("From: Joukkue line: 68", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString95 */
  @Test
  public void testToString95() {    // Joukkue: 95
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("   3  |  Lumo   "); 
    assertEquals("From: Joukkue line: 98", true, joukkue.toString().startsWith("3|Lumo"));  // 
  } // Generated by ComTest END
}