package harkkatyo.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import harkkatyo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.04 13:16:09 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KilpailutTest {



  // Generated by ComTest BEGIN
  /** testAnnaKilpailut31 */
  @Test
  public void testAnnaKilpailut31() {    // Kilpailut: 31
    Kilpailut kil = new Kilpailut(); 
    Kilpailu sm1 = new Kilpailu(1); kil.lisaa(sm1); 
    List<Kilpailu> loytyneet; 
    loytyneet = kil.annaKilpailut(1); 
    assertEquals("From: Kilpailut line: 39", 1, loytyneet.size()); 
    assertEquals("From: Kilpailut line: 40", true, loytyneet.get(0) == sm1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta72 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta72() throws SailoException {    // Kilpailut: 72
    Kilpailut kilpailut = new Kilpailut(); 
    Kilpailu SM1 = new Kilpailu(); SM1.vastaaSMKisat(2); 
    Kilpailu SM2 = new Kilpailu(); SM2.vastaaSMKisat(1); 
    Kilpailu SM3 = new Kilpailu(); SM3.vastaaSMKisat(2); 
    String tiedNimi = "koerekisteri"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    kilpailut.lueTiedostosta(tiedNimi); 
    kilpailut.lisaa(SM1); 
    kilpailut.lisaa(SM2); 
    kilpailut.lisaa(SM3); 
    kilpailut.tallenna(tiedNimi); 
    kilpailut = new Kilpailut(); 
    kilpailut.lueTiedostosta(tiedNimi); 
    kilpailut.lisaa(SM1); 
    kilpailut.tallenna(tiedNimi); 
  } // Generated by ComTest END
}